site_name: Lethean Documentation
copyright: Copyright &copy; 2017 - 2024 LetheanVPN
repo_url: https://github.com/letheanVPN/documentation
repo_name: letheanVPN/documentation
edit_uri: edit/main/docs/
site_url: https://lt.hn
theme:
  name: material
  font: 
    text: "Roboto"
    code: "Roboto Mono"
  language: en
  logo: images/lethean-logo.png
  icon:
    repo: fontawesome/brands/git-alt
    code: octicons/alert-24
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - toc.integrate
    - content.tabs.link
    - content.action.edit
    - content.action.view

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/letheanVPN
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lthn
    - icon: fontawesome/brands/github
      link: https://github.com/letheanVPN
extra_css:
  - stylesheets/extra.css
plugins:
  - offline
  - privacy
  - optimize
  - social
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - search:
      lang:
        - en
  - git-committers:
      repository: letheanVPN/documentation
      branch: main
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
