site_name: Lethean Documentaton
copyright: Copyright &copy; 2017 - 2022 LetheanVPN
repo_url: https://github.com/letheanVPN/documentation
repo_name: letheanVPN/documentation
edit_uri: edit/main/docs/
site_url: https://docs.lt.hn
theme:
  name: material
  font: false
  language: en
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light-blue
      accent: blue
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue-grey
      accent: blue
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/letheanVPN
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lthn
    - icon: fontawesome/brands/github
      link: https://github.com/letheanVPN

plugins:
  - social
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - search:
      lang:
        - en
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.superfences